service: injest-api

frameworkVersion: ">=1.1.0"

custom:
  bucket: trojan-faces

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:PutObject
        - s3:PutObjectAcl
      Resource: "arn:aws:s3:::${self:custom.bucket}/*"

functions:
  injest:
    handler: index.injest
    memorySize: 128
    environment:
      BUCKET: ${self:custom.bucket}
    events:
      - http: 
          path: image
          method: post
          cors: true